# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: cadfe1d1430ef7f769e1ef41e15ad56d8e2f2290b428e6d4ae8d96c511b103c4a4394b5d0a4a5b617f1a18f8c9a4ff9125e8b8ce27ac29db35c5af46428d7a71

test:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: 5b6f471d1168165fc00f19e330e07717af3809e45c8e4c1f6d51ba638a9153804cc407e91914bb6a758a5af656288673d115acae580c20bac53f783d98de7091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
